EXTENDS: https://raw.githubusercontent.com/ScribeMD/.github/0.14.2/.github/base.mega-linter.yaml
JAVASCRIPT_ES_CLI_EXECUTABLE: [node, .yarn/releases/yarn-4.0.2.cjs, run, eslint]
TYPESCRIPT_ES_CLI_EXECUTABLE: [node, .yarn/releases/yarn-4.0.2.cjs, run, eslint]
